name: conftest
on:
  pull_request:
    paths:
      - '.github/workflows/**'
jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'fundapps/opa-policies'
          token: ${{ secrets.CROSS_REPO_TOKEN }}
          path: opa-policies
      - uses: artis3n/setup-conftest@v0.1.1

      - id: conftest-test
        run: conftest test ./.github/workflows/ -p opa-policies/policies | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" | sed 's/WARN/**WARN**/g;s/FAIL/**FAIL**/g'
      - id: conftest-warn-fail-count
        run: echo "::set-output name=conftest-warn-fail-count::$(echo '${{ steps.conftest-test.outputs.stdout }}' | grep -e "WARN" -e "FAIL" | wc -l)"
        shell: bash

      - name: Find Release Comment
        uses: peter-evans/find-comment@v1
        id: release-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: "#### Current Release:"

      - name: Create or Update Release Comment
        uses: peter-evans/create-or-update-comment@v1
        if:  ${{ steps.conftest-warn-fail-count.outputs.conftest-warn-fail-count != 0 }}
        with:
          comment-id: ${{ steps.release-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## OPA Conftest results:
            ```
            WARNS/FAILS: ${{ steps.conftest-warn-fail-count.outputs.conftest-warn-fail-count }}

            ${{ steps.conftest-test.outputs.stdout }}
            ```
          edit-mode: replace
